title: catalyst-flow's blog
description: 死生从此各西东
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  toc_levels: 1..6  # 设置目录生成的标题层级，默认 1..6
lsi: false
safe: true
source: 
incremental: false
highlighter: rouge