title: catalyst-flow's blog
description: 死生从此各西东
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-table-of-contents
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
lsi: false
safe: true
source: 
incremental: false
highlighter: rouge